// <auto-generated />
using System;
using Dynaframe3.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dynaframe3.Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20220217023113_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Dynaframe3.Shared.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BlurBoxMargin")
                        .HasColumnType("REAL");

                    b.Property<float>("BlurBoxSigmaX")
                        .HasColumnType("REAL");

                    b.Property<float>("BlurBoxSigmaY")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrentPlayList")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTimeFontFamily")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTimeFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("DynaframeIP")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExpandDirectoriesByDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FadeTransitionTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideInfoBar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoreFolders")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageStretch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InclusiveTagFilters")
                        .HasColumnType("TEXT");

                    b.Property<int>("InfoBarFontSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InfoBarState")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListenerPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfSecondsToShowIP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OXMOrientnation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PlaybackFullVideo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RefreshDirctories")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReloadSettings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteClients")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScreenStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchDirectories")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowEXIFData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInfoDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowInfoFileName")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShowInfoIP")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Shuffle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SlideShowPaused")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlideshowTransitionTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoStretch")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VideoVolume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("Dynaframe3.Shared.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastCheckin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ip")
                        .HasDatabaseName("ix_Device_Ip");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Dynaframe3.Shared.AppSettings", b =>
                {
                    b.HasOne("Dynaframe3.Shared.Device", null)
                        .WithOne("AppSettings")
                        .HasForeignKey("Dynaframe3.Shared.AppSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dynaframe3.Shared.Device", b =>
                {
                    b.Navigation("AppSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
